server:
  port: 7081
  environment: development
db:
  host: '40swap-postgres-backend'
  port: 5432
  username: '40swap'
  password: '40swap'
  database: '40swap'
  synchronize: false
  migrationsRun: true
bitcoin:
  network: regtest
  requiredConfirmations: 3
nbxplorer:
  baseUrl: http://nbxplorer:32838/v1/cryptos
  fallbackFeeRate: 10
  longPollingTimeoutSeconds: 60
lnd:
  socket: 'alice:10009'
  cert: '/shared/lnd/alice/tls.cert'
  macaroon: '/shared/lnd/alice/admin.macaroon'
mempoolBlockExplorer:
  url: http://mempool-frontend-btc:8080
  useFeeEstimator: true
swap:
  feePercentage: 0.5
  minimumAmount: 0.00200000
  maximumAmount: 0.01300000
  expiryDuration: PT30M
  lockBlockDelta:
    minIn: 144
    in: 432
    out: 144
