name: 40swap

x-40swap-service: &40swap-service
  profiles: ["40swap"]
  restart: unless-stopped

services:
  40swap-postgres-backend:
    <<: *40swap-service
    image: "postgres:16.4"
    container_name: 40swap_postgres_backend
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: "40swap"
      POSTGRES_PASSWORD: "40swap"
      POSTGRES_DB: "40swap"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U 40swap"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - 40swap-postgres-backend-data:/var/lib/postgresql/data

  40swapd-postgres-bob:
    <<: *40swap-service
    image: "postgres:16.4"
    container_name: 40swapd_postgres_bob
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: "40swap"
      POSTGRES_PASSWORD: "40swap"
      POSTGRES_DB: "40swap"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U 40swap"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - 40swapd-postgres-bob-data:/var/lib/postgresql/data

  40swapd-postgres-carol:
    <<: *40swap-service
    image: "postgres:16.4"
    container_name: 40swapd_postgres_carol
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: "40swap"
      POSTGRES_PASSWORD: "40swap"
      POSTGRES_DB: "40swap"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U 40swap"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - 40swapd-postgres-carol-data:/var/lib/postgresql/data

  40swapd-bob:
    <<: *40swap-service
    image: ghcr.io/40acres/40swap/40swapd:master
    container_name: 40swapd_bob
    depends_on:
      40swapd-postgres-bob:
        condition: service_healthy
    environment:
      40SWAPD_DB_HOST: 40swapd-postgres-bob
      40SWAPD_DB_PORT: 5432
      40SWAPD_DB_USER: 40swap
      40SWAPD_DB_PASSWORD: 40swap
      40SWAPD_DB_NAME: 40swap
      40SWAPD_GRPC_PORT: 50051
      40SWAPD_SERVER_URL: http://40swap-backend:7081
      40SWAPD_REGTEST: "true"
      40SWAPD_LND_HOST: bob:10009
      40SWAPD_TLS_CERT: /root/.lnd/tls.cert
      40SWAPD_MACAROON: /root/.lnd/data/chain/bitcoin/regtest/admin.macaroon
      MEMPOOL_ENDPOINT: http://mempool-frontend-btc:8080/api
    volumes:
      - bob_lnd_data:/root/.lnd:ro

  40swapd-carol:
    <<: *40swap-service
    image: ghcr.io/40acres/40swap/40swapd:master
    container_name: 40swapd_carol
    depends_on:
      40swapd-postgres-carol:
        condition: service_healthy
    environment:
      40SWAPD_DB_HOST: 40swapd-postgres-carol
      40SWAPD_DB_PORT: 5432
      40SWAPD_DB_USER: 40swap
      40SWAPD_DB_PASSWORD: 40swap
      40SWAPD_DB_NAME: 40swap
      40SWAPD_GRPC_PORT: 50051
      40SWAPD_SERVER_URL: http://40swap-backend:7081
      40SWAPD_REGTEST: "true"
      40SWAPD_LND_HOST: carol:10009
      40SWAPD_TLS_CERT: /root/.lnd/tls.cert
      40SWAPD_MACAROON: /root/.lnd/data/chain/bitcoin/regtest/admin.macaroon
      MEMPOOL_ENDPOINT: http://mempool-frontend-btc:8080/api
    volumes:
      - carol_lnd_data:/root/.lnd:ro

  40swap-backend:
    <<: *40swap-service
    image: ghcr.io/40acres/40swap-server-backend:master-506
    container_name: 40swap_backend
    depends_on:
      40swap-postgres-backend:
        condition: service_healthy
      nbxplorer:
        condition: service_started
    volumes:
      - alice_lnd_data:/shared:ro
      - ./40swap.conf.yaml:/etc/40swap/40swap.conf.yaml:ro

volumes:
  40swap-postgres-backend-data:
  40swapd-postgres-bob-data:
  40swapd-postgres-carol-data:
  alice_lnd_data:
  bob_lnd_data:
  carol_lnd_data:
